#pragma once
#include "lazy_imp.hpp"

#define	VirtualProtect	LI_FN(VirtualProtect)
 #define	VirtualFree	LI_FN(VirtualFree)
 #define	GetCurrentProcess	LI_FN(GetCurrentProcess)
 #define	VirtualAlloc	LI_FN(VirtualAlloc)
 #define	FlushInstructionCache	LI_FN(FlushInstructionCache)
 #define	lstrcmpA	LI_FN(lstrcmpA)
 #define	lstrcmpiA	LI_FN(lstrcmpiA)
 #define	GetModuleFileNameA	LI_FN(GetModuleFileNameA)
 #define	HeapFree	LI_FN(HeapFree)
 #define	lstrlenA	LI_FN(lstrlenA)
 #define	lstrcatA	LI_FN(lstrcatA)
 #define	GetModuleHandleA	LI_FN(GetModuleHandleA)
// #define	lstrcpyA	LI_FN(lstrcpyA)
// #define	HeapAlloc	LI_FN(HeapAlloc)
// #define	GetProcessHeap	LI_FN(GetProcessHeap)
// #define	GetPrivateProfileStringA	LI_FN(GetPrivateProfileStringA)
// #define	ExpandEnvironmentStringsW	LI_FN(ExpandEnvironmentStringsW)
// #define	LoadLibraryA	LI_FN(LoadLibraryA)
// #define	LoadLibraryW	LI_FN(LoadLibraryW)
// #define	GetProcAddress	LI_FN(GetProcAddress)
// #define	Process32First	LI_FN(Process32First)
// #define	TerminateProcess	LI_FN(TerminateProcess)
// #define	OpenProcess	LI_FN(OpenProcess)
// #define	CreateToolhelp32Snapshot	LI_FN(CreateToolhelp32Snapshot)
// #define	Process32Next	LI_FN(Process32Next)
// #define	CloseHandle	LI_FN(CloseHandle)
// #define	CreateThread	LI_FN(CreateThread)
// #define	ExitProcess	LI_FN(ExitProcess)
// #define	MessageBoxA	LI_FN(MessageBoxA)
// #define	WSAEnumProtocolsW	LI_FN(WSAEnumProtocolsW)
// #define	WSAStartup	LI_FN(WSAStartup)
// #define	WSCGetProviderPath	LI_FN(WSCGetProviderPath)
// #define	WSACleanup	LI_FN(WSACleanup)
// #define	inet_addr	LI_FN(inet_addr)
